version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    rust: latest
  jobs:
    post_create_environment:
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
      - source "$HOME/.cargo/env"
      - echo "Rust installed: $(rustc --version)"
    pre_build:
      - pip install maturin>=1.7,<2.0
      # Navigate to project root explicitly
      - cd $READTHEDOCS_PROJECT_DIRECTORY
      - maturin develop --release
      - echo "Python path: $(python -c 'import sys; print(sys.path)')"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

python:
  install:
    - method: pip
      path: .
      extra_requirements: [docs]
  system_packages: true